---
abstract: 'Extensible Fake Data Generator'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires:
  Data::Object::Class: '2.02'
  Data::Object::ClassHas: '2.01'
  Data::Object::Plugin: '0.01'
  Data::Object::Role: '2.01'
  Data::Object::Role::Pluggable: '0.01'
  Data::Object::Role::Proxyable: '2.03'
  Data::Object::Role::Throwable: '2.00'
  Data::Object::RoleHas: '2.01'
  Test::Auto: '0.07'
  perl: '5.014'
  routines: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Faker
requires:
  Data::Object::Class: '2.02'
  Data::Object::ClassHas: '2.01'
  Data::Object::Plugin: '0.01'
  Data::Object::Role: '2.01'
  Data::Object::Role::Pluggable: '0.01'
  Data::Object::Role::Proxyable: '2.03'
  Data::Object::Role::Throwable: '2.00'
  Data::Object::RoleHas: '2.01'
  perl: '5.014'
  routines: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/cpanery/faker/issues
  homepage: http://metacpan.org/release/Faker/
  repository: git://github.com/cpanery/faker.git
version: '1.05'
x_authority: cpan:AWNCORP
x_contributors:
  - 'Al Newkirk <anewkirk@ana.io>'
x_generated_by_perl: v5.32.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: Apache-2.0
